version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://code-build-cicd/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name doordash-lambda-function --s3-bucket code-build-cicd --s3-key deployment_package.zip 
      - echo "Deployment complete!"